name: Test Pipeline

on:
  schedule:
    - cron: '30 23 * * *' 
  push: 
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

      - name: Archive Logs
        if: always()  # This ensures logs are saved even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: automation-logs
          path: logs/

      - name: Archive Extent Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extent-reports
          path: reports/

      - name: Notify test success or failure
        run: echo "Tests completed."
