name: Test Automation Framework WorkFlow

on:
  schedule:
   - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

        
    - name: Running Test with maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
    
    - name: Upload logs Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Log Artifacts
        path: logs/

    - name: Upload Reports Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Report Artifacts
        path: report.html

    - name: Test Status
      run: echo " Test Execution Completed" 





      

 
